# Generated by Django 4.2.3 on 2023-07-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0002_alter_book_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
